# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Позиция')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('heading', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('subheading', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('url', models.CharField(max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('position',),
            },
        ),
    ]
