# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
                ('expanded', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.ManyToManyField(to='food.FoodCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(to='food.FoodTag'),
        ),
    ]
