# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='food.FoodTag'),
        ),
    ]
