# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='price',
            new_name='raw_price',
        ),
    ]
