# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20160124_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
    ]
