# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20160526_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Значение <=1 — проценты, значение >1 — абсолютное значение', max_digits=7, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Применяется к'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='expanded',
            field=models.BooleanField(default=True, verbose_name='Развёрнута'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимая'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ManyToManyField(to='food.FoodCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='position',
            field=models.IntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='raw_price',
            field=models.IntegerField(verbose_name='Первоначальная цена'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fooditems', to='food.FoodTag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимое'),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='position',
            field=models.IntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимый'),
        ),
    ]
