# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20160529_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
