# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20160102_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ('position',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ('position',), 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='foodtag',
            options={'ordering': ('position',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
