# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20160528_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.FoodCategory', verbose_name='Категории'),
            preserve_default=False,
        ),
    ]
