# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160529_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='promo_images/', verbose_name='Изображение'),
        ),
    ]
