# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_gift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='history_price',
        ),
    ]
