# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_move_address_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
