# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_foodcategory_slug'),
        ('order', '0004_auto_20160331_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['requirement']},
        ),
        migrations.AddField(
            model_name='order',
            name='gift_food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodItem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='history_price',
            field=models.IntegerField(null=True),
        ),
    ]
