# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20160529_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Улица'),
        ),
    ]
