# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказов',
                'proxy': True,
                'indexes': [],
            },
            bases=('order.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodItem', verbose_name='Подарок'),
        ),
    ]
