# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20170420_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('position',), 'verbose_name': 'Содержимое корзины', 'verbose_name_plural': 'Содержимое корзины'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
