# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 01:32
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20170423_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=15, primary_key=True, serialize=False),
        ),
    ]
