# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20170424_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Квартира'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
