# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:21
from __future__ import unicode_literals

from django.db import migrations

from food.serializers import FoodItemMetaSerializer


class CustomFoodItemMetaSerializer(FoodItemMetaSerializer):
    def get_fields(self):
        fields = super(CustomFoodItemMetaSerializer, self).get_fields()
        fields.pop('price')
        return fields


def fill_cart_meta_field(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    for order in Order.objects.all().prefetch_related('cart__cartitem_set__product'):
        print(order.id)
        if not order.cart:
            continue
        cart_items = {}
        cart_item_ids = []
        subtotal = 0
        for cart_item in order.cart.cartitem_set.all():
            food_item = cart_item.product
            food_item_serialized = CustomFoodItemMetaSerializer(food_item).data
            food_item_serialized['price'] = cart_item.history_price
            food_item_serialized['quantity'] = cart_item.quantity
            cart_items[food_item.id] = food_item_serialized
            cart_item_ids.append(food_item.id)
            subtotal += cart_item.quantity * cart_item.history_price
        cart_meta = {
            'cart_items': cart_items,
            'cart_item_ids': cart_item_ids,
            'subtotal': subtotal,
        }
        order.cart_meta = cart_meta
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20170505_2003'),
        ('food', '0017_remove_amount_from_title'),
    ]

    operations = [
        migrations.RunPython(fill_cart_meta_field)
    ]
