# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 06:24
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20160528_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Позиция'),
        ),
    ]
