# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20170325_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
