# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:59
from __future__ import unicode_literals
import re

from django.db import migrations


def populate_amount_field(apps, schema_editor):
    RE_PATTERN = r'.+ (\d+) ?шт\.?'
    FoodItem = apps.get_model("food", "FoodItem")
    for food in FoodItem.objects.filter(title__iregex=RE_PATTERN):
        print(food.title)
        m = re.match(RE_PATTERN, food.title)
        food.amount = '{} шт.'.format(m[1])
        food.save()


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_fooditem_amount'),
    ]

    operations = [
        migrations.RunPython(populate_amount_field),
    ]
