# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_remove_amount_from_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='expanded',
        ),
    ]
